language: perl
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mecab mecab-ipadic-utf8 libmecab-dev
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"

